---
title: 'Project 2: Modeling, Testing, and Predicting'
author: "SDS348"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

```{r setup, include=FALSE}
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})

knitr::opts_chunk$set(echo = TRUE, eval = TRUE,fig.align="center",warning=FALSE,message=FALSE,fig.width=8, fig.height=5, linewidth=60)
options(tibble.width = 100,width = 100)
library(tidyverse)
library(sandwich)
library(lmtest)
```

# Modeling

## **0. (5 pts)** 

```{R}
library(robustbase)
crohnD = CrohnD

```

This data set was from a study on 117 patients (therefore, 117 observations) affected by Crohn's disease, which is a chronic inflammatory disease that is localized in the intestines. It contains 9 variables: patient ID (unique number for each patient), number of adverse events, BMI (with units of kg/m^2), height (in centimeters), country (dichotomous variable, patient is either from country 1 or country 2), sex (male or female), age (in years), weight (in kilograms), and treatment (placebo, drug 1, or drug 2).

## **1. (15 pts)** 


```{R}
library(rstatix)

group <- crohnD$treat 
DVs <- crohnD %>% select(nrAdvE,BMI,height,age,weight)

#Test multivariate normality for each group (null: assumption met)
sapply(split(DVs,group), mshapiro_test)

#p<.05, so I stopped (assumption violated). 

man1 = manova(cbind(nrAdvE,BMI,height,age,weight)~treat,data=crohnD)
summary(man1)

1-(0.95^1) # chance of type 1 error 
0.05/1 # calculation of bonferroni correction
```

The numerical variables of number of adverse events, weight, height, and BMI were all tested to see if there was a mean difference across the three treatment groups. Multivariate normality was tested for each group, with all three groups reporting p values of less than 0.05, thus violating this assumption. The MANOVA test showed no significance, and so no univariate ANOVAs nor post-hoc t-tests were ran. The alpha value remained at 0.05. The chances of a type 1 error occuring is 5%. Regarding MANOVA assumptions, this is most like not a random sample, since this dataset consists patient data that was used in a research study. We can assume that the observations are independent as each observation represents an individual patient. This data does not meet the multivariate normality assumption, meaning that the further assumptions of homogeneity of within-group covariance matrices and lack of extreme univariate / covariate outliers were also not met. This data also most likely does not meet the MANOVA assumption of no multicolinearity, since the variables of weight/height/BMI are related to each other, and thus correlated.


# **2. (10 pts)** 


```{R}
library(vegan)
dist = DVs %>% dist()
adonis(dist~treat,data=crohnD)

#calculations for observed F
SSW = crohnD %>% group_by(treat) %>% select(nrAdvE, BMI, height, weight) %>% do(d=dist(.[2:3],"euclidean")) %>% ungroup() %>% summarize(sum(d[[1]]^2)/50 + sum(d[[2]]^2)/50 + sum(d[[3]]^2)/50)%>%pull
SST = sum(dist^2) / 117
obs_F = ((SST-SSW)/2)/(SSW/114)

Fvals = replicate(1000,{
new = crohnD %>% mutate(treat=sample(treat))
SSW = new %>% group_by(treat) %>% select(nrAdvE, BMI, height, weight) %>% do(d=dist(.[2:3],"euclidean")) %>% ungroup() %>% summarize(sum(d[[1]]^2)/50 + sum(d[[2]]^2)/50 + sum(d[[3]]^2)/50) %>% pull
((SST-SSW)/2)/(SSW/114) })

mean(Fvals > obs_F)
{hist(Fvals, prob = T); abline(v = obs_F, col="blue", add = T)}

```

Null hypothesis: The center and spread of the three treatment groups were the same.

Alternate hypothesis: At least one of the treatment groups' center and/or spread was different from the other groups. 

Since the p-value is greater than 0.05, we fail to reject the null hypothesis, meaning that the three treatment groups do not have significantly different centers nor spreads.

# **3. (35 pts)** 


```{R}

crohnD$nrAdvEc = crohnD$nrAdvE - mean(crohnD$nrAdvE)
crohnD$heightc = crohnD$height - mean(crohnD$height)
crohnD$weightc = crohnD$weight - mean(crohnD$weight)
crohnD$BMIc = crohnD$BMI - mean(crohnD$BMI)

crohnD = crohnD %>% mutate(treat = as.factor(treat))
fit = lm(nrAdvE ~ treat*weightc, data = crohnD)
summary(fit)
coef(fit)

```

The predicted number of adverse events for someone with an average weight in the placebo treatment group is 2.434 events. Individuals with an average weight in the d1 treatment group had 0.824 fewer adverse events than those in the placebo treatment group. Individuals with an average weight in the d2 treatment group had 0.237 fewer adverse events than those in the placebo treatment group. As weight increases by 1 for individuals in the placebo treatment group, the predicted number of adverse events goes up by 0.031. The slope for weight on the number of adverse events for the d1 treatment group is 0.0103 lower than that for the placebo treatment group. The slope for weight on the number of adverse events for the d2 treatment group is 0.0533 lower than that for the placebo treatment group.

```{R}
crohnD %>% ggplot(aes(weightc, nrAdvE, color=treat)) +
  geom_point() +
  geom_smooth(method = 'lm', se = F, fullrange = T) +
  ggtitle("Linear Regression Prediction of Number of Adverse Events with Weight and Treatment") +
  ylab("Number of Adverse Events") +
  xlab("Weight") +
  labs(color = "Treatment")

#normality check
residual = lm(nrAdvE ~ treat*weightc, data=crohnD)$residuals
shapiro.test(residual) # p < 0.05, fails normality assumption

#homoskedasticity check
bptest(fit) # fail to reject (p > 0.05), it is homoskedastic

#linearity check
crohnD %>% filter(treat == "placebo") %>% ggplot(aes(weightc, nrAdvE)) +
  geom_point()

crohnD %>% filter(treat == "d1") %>% ggplot(aes(weightc, nrAdvE)) +
  geom_point()

crohnD %>% filter(treat == "d2") %>% ggplot(aes(weightc, nrAdvE)) +
  geom_point()

#linearity is not clear from the graphs above

#robust SE test
coeftest(fit, vcov=vcovHC(fit))

```

The robust standard errors test showed that no variable demonstrated any significance, which is in line with the initial linear regression test. According to the R^2 value calculated in the initial linear regression, our model explains 3.21% of variability in number of adverse events.

# **4. (5 pts)** 


```{R}
boot_data = sample_frac(crohnD, replace = T)
samp_distn = replicate(5000, {
boot_data = sample_frac(crohnD, replace=T) 
fit = lm(nrAdvE~weightc*treat, data=boot_data)
coef(fit)
})
summary(fit)

samp_distn %>% t %>% as.data.frame %>% summarize_all(sd)
```
The bootstrapped standard errors calculated above are incredibly similar to the original and robust standard errors calculated earlier. The p values remain to be the same, and thus the bootstrapped standard errors do not make any of the variables significant.
# **5. (25 pts)** 


```{R}
crohnD = crohnD %>% mutate(treatb = ifelse(treat=="placebo",0,1))
fit1 = glm(treatb~weightc+nrAdvE, data = crohnD, family = binomial(link = "logit"))
coeftest(fit1)
exp(coef(fit1))

predicted = predict(fit1, type = "response")
pred = ifelse(predicted > .5,1,0)
table(prediction=pred, truth = crohnD$treatb) %>% addmargins

#accuracy
(2+78)/117

#TPR 
78/78

#TNR
2/39

#PPV
78/115
```

For every unit increase in weight, the odds of a patient receiving a drug that isn't a placebo increases by 1.006. For every unit increase in the number of adverse events, the odds of a patient receiving a drug that isn't a placebo increases by 0.928.The model has an accuracy of 68.38%; that is, the model correctly classified 68.38% of cases. Additionally, the model has a TPR of 100%, meaning that 100% of patients actually receiving the drug were correctly classified. The TNR of the model was 5.13%, meaning that 5.13% of patients in the placebo group were correctly classified. This model also has a PPV of 67.83%, meaning that 67.83% of patients classified as being from a drug group were actually from a drug group.

```{R}
crohnD$logit = predict(fit1, data = crohnD, type = "link")
crohnD$treatb = factor(crohnD$treatb, levels = c("1","0"))
crohnD = crohnD %>% mutate(treatment = ifelse(treat=="placebo", "placebo","drug"))

crohnD %>% ggplot(aes(logit, fill = treatment)) +
  geom_density(alpha = .3) +
  geom_vline(xintercept = 0, lty = 2) + 
  ggtitle("Log-odds Density by Treatment Group")

library(plotROC)
crohnD = crohnD %>% mutate(treatb=ifelse(treat=='placebo',0,1))
crohnD$prob = predict(fit1, type = "response")
ROCplot = ggplot(crohnD) + geom_roc(aes(d = treatb, m = prob), n.cuts = 0)
ROCplot

calc_auc(ROCplot)
```

The ROC plot above shows an AUC value of 0.569, meaning that this a poor model at predicting a patient's treatment group.


# **6. (25 pts)** 

```{R}

class_diag <- function(probs,truth){
  #CONFUSION MATRIX: CALCULATE ACCURACY, TPR, TNR, PPV
  tab<-table(factor(probs>.5,levels=c("FALSE","TRUE")),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  f1=2*(sens*ppv)/(sens+ppv)

  if(is.numeric(truth)==FALSE & is.logical(truth)==FALSE) truth<-as.numeric(truth)-1
  
  #CALCULATE EXACT AUC
  ord<-order(probs, decreasing=TRUE)
  probs <- probs[ord]; truth <- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup<-c(probs[-1]>=probs[-length(probs)], FALSE)
  TPR<-c(0,TPR[!dup],1); FPR<-c(0,FPR[!dup],1)
  n <- length(TPR)
  auc<- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,f1,auc)
}

fit = glm(treatb~heightc+BMIc, data = crohnD, family = "binomial")
prob = predict(fit, type = "response")
class_diag(prob,crohnD$treatb)


```

In-sample diagnostics of the linear regression model predicting treatment group with heigh and BMI were ran. Accuracy was 66.67%, meaning that the model correctly classified 66.67% of cases. The sensitivity was 1, meaning that 100% of actual drug group patients were correctly classified as being of the drug group. The specificity was 0, meaning that none of the patients from the placebo group were correctly classified. The PPV is 66.67%, meaning that 66.67% of those classified as part of the drug group actually are a part of the drug group.


```{R}
#10 fold CV
crohnD <- crohnD %>% mutate(y=ifelse(treatb=="0",0,1))
set.seed(1234)
k=10 
data<-crohnD[sample(nrow(crohnD)),] 
folds<-cut(seq(1:nrow(crohnD)),breaks=k,labels=F) 
diags<-NULL
for(i in 1:k){

train<-data[folds!=i,]
test<-data[folds==i,]
truth<-test$y

fit<-glm(y~heightc+BMIc,data=train,family="binomial")

probs<-predict(fit,newdata = test,type="response")

diags<-rbind(diags,class_diag(probs,truth))
}
summarize_all(diags,mean) 
```
The 10 fold cross validation model demonstrated 66.52% accuracy, 100% sensitivity, 0% specificity, and 66.52% PPV. The AUC value is 0.463, thus indicating that this is a very poor model for predicting treatment group.

```{R}
#LASSO regression
library(glmnet)
crohnD2 = crohnD %>% select(2:9,treatb,-treat)
y = as.matrix(crohnD2$treatb)
x = model.matrix(treatb~1+.,data=crohnD2)
head(x)

cv = cv.glmnet(x,y, family = "binomial")
lasso = glmnet(x,y, family = "binomial", lambda = cv$lambda.1se)
coef(lasso)
```

From the LASSO regression test, it seems that none of the variables were retained. As a result, we will be arbitrarily choosing number of adverse events for the next model.

```{R}
set.seed(1234)
k=10 
data<-crohnD[sample(nrow(crohnD)),] 
folds<-cut(seq(1:nrow(crohnD)),breaks=k,labels=F) 
diags<-NULL
for(i in 1:k){

train<-data[folds!=i,]
test<-data[folds==i,]
truth<-test$treatb

fit<-glm(treatb~nrAdvE,data=train,family="binomial")
probs<-predict(fit,newdata = test,type="response")
diags<-rbind(diags,class_diag(probs,truth))

}
summarize_all(diags,mean) 
```
The AUC for the out-of-sample model is 0.534, which is better than the originial in-sample model's AUC value of 0.463. Since this model has a larger AUC value more than just a few hundredths, I assume that the original model was overfitted.